#!/bin/bash

## Configuration Options
CHECK_DELAY=5
IRC_PORT="6667"
IRC_CHANNEL="#score"
IRC_NICK="scorebot"

## Files
ICMP_CONFIG="icmp"
WEB_CONFIG="web"
DNS_CONFIG="dns"
IRC_CONFIG="irc"
SMTP_CONFIG="smtp"

## ICMP Check
icmp ()
{
	echo "$(date) [+] Executing ICMP check"
	while read line; do
		ping -c 1 "$line" 2>&1 >/dev/null &&\
		echo "$(date) [ICMP] Success $line" ||\
		echo "$(date) [ICMP] Failure $line"
	done < "$ICMP_CONFIG"
}

## Web Content Check
webcontent ()
{
	echo "$(date) [+] Executing web content check"
	while read line; do
		SITE="$(echo $line | awk '{print $1}')"
		HASH="$(echo $line | awk '{print $2}')"
		NEW_HASH="$(wget -q -O- \"$SITE\" | md5sum | awk '{print $1}')"
		
		if [ "$NEW_HASH" == "$HASH" ]; then
			echo "$(date) [Web-Content] Success $SITE $HASH"
		else
			echo "$(date) [Web-Content] Failure $SITE $HASH"
		fi
	done < "$WEB_CONFIG"
}

## Web Availability Check
webavail ()
{
	echo "$(date) [+] Executing web availability check"
	while read line; do
		SITE="$(echo $line | awk '{print $1}')"
		
		curl -s "$SITE" 2>&1 >/dev/null &&\
		echo "$(date) [Web-Availability] Success $SITE $HASH" ||\
		echo "$(date) [Web-Availability] Failure $SITE $HASH"
	done < "$WEB_CONFIG"
}
## DNS Dig Check
dnsdig ()
{
	echo "$(date) [+] Executing DNS dig check"
	while read line; do
		DNS_SERVER="$(echo $line | cut -d ':' -f 1)"
		DNS_DOMAIN="$(echo $line | cut -d ':' -f 2)" 
		
		dig @"$DNS_SERVER" "$DNS_DOMAIN" |\
		grep -i -q noerror &&\
		echo "$(date) [DNS-DIG] Success $DNS_SERVER $DNS_DOMAIN" ||\
		echo "$(date) [DNS-DIG] Failure $DNS_SERVER $DNS_DOMAIN"
	done < "$DNS_CONFIG"
}

## IRC Check
irc ()
{
	echo "$(date) [+] Executing IRC check"
	while read IRC_SERVER; do
		RESULT=$(echo -e "NICK $NICK\nUSER $NICK * 8 $NICK\nJOIN #score\nPRIVMSG #score :Score check passed\nQUIT" | nc $IRC_SERVER $IRC_PORT )
		regex=":.* [0-9]\{3\} .* "
		res=$(echo "$RESULT" | grep -o "$regex")
		if [ "$res" != "" ]; then
			echo "$(date) [IRC] Success [$IRC_SERVER:$IRC_PORT]"
		else
			echo "$(date) [IRC] Failure [$IRC_SERVER:$IRC_PORT]"
		fi
	done < "$IRC_CONFIG"
}

#SMTP
smtp() {
	while read SERVER; do
		PORT="25"
		SENDR="scorebot@rit.ccdc"
		RECVR="root@rit.ccdc"
		RESULT=$(echo -e "HELO scorebot\nMAIL FROM: $SENDR\nRCPT TO: $RECVR\nDATA\nSubject: Test Passed\n.\nQUIT" | nc -w 2 $SERVER $PORT 2>/dev/null )
		res=$(echo "$(echo -e "$RESULT" | awk '{print $1}' | tail -n 3)")
		if [[ "$(echo $res)" == "354 250 221" || "$res" == "250 221" ]]; then
			echo "$(date) [SMTP] Success [$SERVER:$PORT]"
		else
			echo "$(date) [SMTP] Failed [$SERVER:$PORT]"
		fi
	done < "$SMTP_CONFIG"
}


while [ 1 ]; do
	icmp 
	webcontent
	webavail
	dnsdig
	irc
	smtp
	sleep "$CHECK_DELAY"
done
